### ISSUE TITLE
Cannot launch the app

### ISSUE THREAD

**Issue by sith-on-mars** [flathub/com.adobe.Reader#5]
OS: OpenSUSE MicroOS Gnome

I couldn't launch the app at all. It gave me the following error:

```
dadstick@localhost:~> flatpak run com.adobe.Reader
/app/extra/Adobe/Reader9/Reader/intellinux/bin/acroread: error while loading shared libraries: libcrypto.so.0.9.8: cannot enable executable stack as shared object requires: Permission denied
```

**Comment by hmenke** [comment]
Does it launch if you temporarily `setenforce 0` to disable SELinux?

**Comment by hmenke** [comment]
Can you please test this build? https://nightly.link/hmenke/com.adobe.Reader/workflows/flatpak/master/acroread-x86_64.zip

**Comment by sith-on-mars** [comment]
Thanks. I was able to install runtime but for some reasons I couldn't install the test-build app.

```
Error: Extra data missing in detached metadata
error: Failed to install bundle com.adobe.Reader: Extra data missing in detached metadata
```

**Comment by hmenke** [comment]
Oh no, there is a bug in `flatpak build-bundle` that prevents `extra-data` from being included or downloaded during install: https://github.com/flatpak/flatpak/issues/1334

Sorry, you will have to build the Flatpak yourself from source: https://github.com/hmenke/com.adobe.Reader/tree/master

**Comment by hfiguiere** [comment]
this version of openssl is likely not in the runtime. It's antique, full of security hole.

**Comment by hmenke** [comment]
This version of OpenSSL comes bundled with Adobe Reader. I doubt that it can be substituted with the one from the runtime.

**Comment by Erick555** [comment]
I think something on OP host system prevents loading that lib. I doubt it's selinux.

**Comment by hmenke** [comment]
@sith-on-mars Has this problem been solved for you? https://github.com/flathub/com.adobe.Reader/commit/6018b4bf2cb23727a5dbfc48f654155c930a19ac should have done that.

**Comment by hmenke** [comment]
No further updates since almost one month... closing.

@sith-on-mars Please reopen with more info if the issue persists.
